AllCops:
  NewCops: enable

require:
  - rubocop-performance
  - rubocop-sequel

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Layout/LineLength:
  Enabled: false
